name: Actualizar Kobo a Looker

on:
  schedule:
    # Se ejecuta en el minuto 15 de cada hora
    # PERO solo de Lunes (1) a Viernes (5)
    - cron: '15 * * * 1-5'
  workflow_dispatch: # Permite ejecutar manualmente cualquier día si hace falta

jobs:
  run-etl-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias del sistema
        # Geopandas necesita librerías de C++ (spatialindex) para funcionar en Linux
        # Fiona necesita GDAL para leer KML/KMZ
        run: |
          sudo apt-get update
          sudo apt-get install -y libspatialindex-dev gdal-bin libgdal-dev

      - name: Instalar librerías de Python
        run: |
          pip install -r requirements.txt

      - name: Ejecutar Script Principal
        env:
          KOBO_TOKEN: ${{ secrets.KOBO_TOKEN }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        # Asegúrate de que el nombre del archivo coincida con el de tu repositorio (main.py o main_act_flash.py)
        run: python main_act_flash.py
